name: websockets
description: A platform-independent WebSocket library.
version: 0.2.1+1
author: Steven Roose <stevenroose@gmail.com>
homepage: https://github.com/stevenroose/dart-websockets
environment:
  sdk: '>=1.19.1 <2.0.0'

dependencies:

dev_dependencies:
  test: any